pipeline{
     agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        //retry(1)
    }
     environment {
        appVersion = '' // this will become global, we can use across pipeline
        region = 'us-east-1'
        account_id = '528757792370'
        project = 'expense'
        environment = 'dev'
        component = 'frontend'
    }

    stages{
        stage('read the version'){
            steps{
                dir('frontend') {
                    script{
                        def packageJson = readJSON file: 'package.json'
                        appVersion = packageJson.version
                        echo "App Version: ${appVersion}"
                    }
                }
            }
        }
        //  stage('install dependencies'){
        //     steps{
        //         dir('backend') {
        //             sh 'npm install'
        //         }
        //     }
        // }
        stage('docker image'){
           steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds-dev') {
                    dir('frontend') {
                        sh """
                            aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.${region}.amazonaws.com
                            docker build -t ${account_id}.dkr.ecr.${region}.amazonaws.com/${project}/${environment}/${component}:${appVersion} .
                            docker images
                            docker push ${account_id}.dkr.ecr.${region}.amazonaws.com/${project}/${environment}/${component}:${appVersion}
                        """
                    }
                }
           }
        }
        stage('deploy application'){
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds-dev') {
                    dir('frontend'){
                        sh """
                            aws eks update-kubeconfig --region ${region} --name ${project}-${environment}
                            helm upgrade --install ${component} ./helm \
                            -f ./${component}-values.yml \
                            --set deployment.image.prefix=${account_id}.dkr.ecr.${region}.amazonaws.com/${project}/${environment}/${component} \
                            --set deployment.image.tag=${appVersion} 
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}